services:
  - type: web
    name: pro-env-api
    rootDir: backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start

  - type: static
    name: frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://pro-env-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html