
services:
  # Database PostgreSQL
  postgres:
    image: postgis/postgis:15-3.4
    container_name: sigie_postgres
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-sigie}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-19991}
      POSTGRES_DB: ${DB_NAME:-smart_city}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - sigie_postgres_data:/var/lib/postgresql/data
    networks:
      - environnement_network

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: sigie_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - environnement_network

networks:
  environnement_network:
    driver: bridge

volumes:
  sigie_postgres_data:
  redis_data:
